name: Generate Github top languages
description: Generate Github top languages (within your organizations)
branding:
  icon: bar-chart
  color: purple

inputs:
  botName:
    required: false
    default: "Jan Galek"
    description: "Set bot name for contributors"

  botEmail:
    required: false
    default: "ghome.cz@gmail.com"
    description: "Set bot email address for contributors"
  user:
    required: true
    description: "Github UserName"
  limit:
    required: true
    default: 6
    description: "Limit of languages"
  ignoredOrgsFlag:
    required: true
    default: ""
    description: "Comma-separated list of ignored organizations"
  ignoredReposFlag:
    required: true
    default: ""
    description: "Comma-separated list of ignored repositories"

env:
  GITHUB_TOKEN: "As provided by Github Actions"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --global user.name "${{ inputs.botName }}"
        git config --global user.email "${{ inputs.botEmail }}"
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"

    - name: Build the Go binary
      run: |
        git clone https://github.com/gouef/githubtoplanguages.git
        cd githubtoplanguages
        make install
        go build -o app .
        cp app ./../app
        cd ..
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: Run the Go binary
      run: |
        args=""
        [ -n "${{ inputs.user }}" ] && args="$args -user=${{ inputs.user }}"
        [ -n "${{ inputs.limit }}" ] && args="$args -limit=${{ inputs.limit }}"
        [ -n "${{ inputs.ignoredOrgsFlag }}" ] && args="$args -ignore-orgs=${{ inputs.ignoredOrgsFlag }}"
        [ -n "${{ inputs.ignoredReposFlag }}" ] && args="$args -ignore-repos=${{ inputs.ignoredReposFlag }}"
        
        ./app $args -gh-token=${{ env.GITHUB_TOKEN }}
        rm -R githubtoplanguages
        rm app
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git add ./toplanguages.svg
        if git diff --cached --quiet; then
          echo "Žádné změny, nic k commitování."
        else
          git add .
          git commit -m "[Update] Generate github top language"
          git push origin HEAD:${{ github.event.repository.default_branch }}
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}