name: Create Top Languages

on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
    botName:
      required: false
      default: "Jan Galek"
      description: "Set bot name for contributors"

    botEmail:
      required: false
      default: "ghome.cz@gmail.com"
      description: "Set bot email address for contributors"
    user:
      required: true
      default: "JanGalek"
      description: "Github UserName"
    limit:
      required: true
      default: 6
      description: "Limit of languages"
    ignoredOrgsFlag:
      required: true
      default: "wowmua"
      description: "Comma-separated list of ignored organizations"
    ignoredReposFlag:
      required: true
      default: "wowmua/Maps"
      description: "Comma-separated list of ignored repositories"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run custom action
        uses: gouef/githubtoplanguages@main
        with:
          botName: "Jan Galek"
          botEmail: "ghome.cz@gmail.com"
          user: "JanGalek"
          limit: 6
          ignoredOrgsFlag: "wowmua"
          ignoredReposFlag: "wowmua/Maps"
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}